name = "nekosama-gallery"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "nekosama-gallery-db"
database_id = "b8161388-f20f-4b5c-8e9f-d80134119524"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "nekosama-gallery"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "nekosama-gallery-db"
database_id = "b8161388-f20f-4b5c-8e9f-d80134119524"

[[env.production.r2_buckets]]
binding = "BUCKET"
bucket_name = "nekosama-gallery"